name: Docker Build

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Dockerfile'
      - 'src/**'
      - '.dockerignore'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'Dockerfile'
      - 'src/**'
      - '.dockerignore'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: docker build -t presupuesto-familiar-api .
      
    - name: Test Docker image
      run: |
        docker run --rm -d --name test-app -p 8080:8080 presupuesto-familiar-api
        sleep 10
        curl -f http://localhost:8080/api/health/ping || exit 1
        docker stop test-app 