name: Deploy to Railway

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Build
      run: |
        dotnet restore
        dotnet build --configuration Release
        
    - name: Success
      run: |
        echo "✅ Build completado exitosamente"
        echo "🚀 Listo para desplegar manualmente en Railway"
        echo "📋 Para desplegar automáticamente, configura Railway CLI" 