name: Deploy to Railway

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Build
      run: |
        dotnet restore
        dotnet build --configuration Release
        
    - name: Check Railway secrets
      id: check-secrets
      run: |
        if [ -n "${{ secrets.RAILWAY_TOKEN }}" ] && [ -n "${{ secrets.RAILWAY_SERVICE }}" ]; then
          echo "secrets_configured=true" >> $GITHUB_OUTPUT
        else
          echo "secrets_configured=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Deploy to Railway
      if: steps.check-secrets.outputs.secrets_configured == 'true'
      uses: railway/deploy@v1
      with:
        service: ${{ secrets.RAILWAY_SERVICE }}
        token: ${{ secrets.RAILWAY_TOKEN }}
        
    - name: Skip deployment
      if: steps.check-secrets.outputs.secrets_configured == 'false'
      run: |
        echo "⚠️ Railway secrets no configurados. Saltando despliegue."
        echo "✅ Build completado exitosamente" 